#!/bin/bash

#SBATCH -N 1
#SBATCH -t 10:00:00
#SBATCH -p gpu

module load eb
module load Python/3.6.3-foss-2017b
module load CUDA/9.0.176
module load cuDNN/7.0.5-CUDA-9.0.176
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:/hpc/eb/Debian/cuDNN/7.0.5-CUDA-9.0.176/lib64:$LD_LIBRARY_PATH

cd /home/samigpu/Codes/SolutionDistillation

HEAD_DIR="/home/samigpu/Codes/SolutionDistillation"
CODE_DIR=$HEAD_DIR/distill
DATA_DIR=$HEAD_DIR/data
LOGS_DIR=$HEAD_DIR/logs

export PYTHONPATH=$PYTHONPATH:$HEAD_DIR

python $CODE_DIR/plain_sst_trainer.py --hidden_dim=100 --learning_rate=0.0005 --exp_name=lr0001 &
python $CODE_DIR/plain_sst_trainer.py  --hidden_dim=100 --learning_rate=0.005 --exp_name=lr001 &
python $CODE_DIR/plain_sst_trainer.py --hidden_dim=50 --learning_rate=0.005 --exp_name=lr001 &
python $CODE_DIR/plain_sst_trainer.py --hidden_dim=50 --learning_rate=0.0005 --exp_name=lr0001 &
wait
