#!/bin/bash

#SBATCH -n 1
#SBATCH --job-name=plain_lstm_64
#SBATCH --time=5:00:00
#SBATCH --partition=gpu

module load eb
module load Python/3.6.3-foss-2017b
module load CUDA/9.0.176
module load cuDNN/7.0.5-CUDA-9.0.176
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:/hpc/eb/Debian/cuDNN/7.0.5-CUDA-9.0.176/lib64:$LD_LIBRARY_PATH

cd /home/samigpu/Codes/SolutionDistillation

HEAD_DIR="/home/samigpu/Codes/SolutionDistillation"
CODE_DIR=$HEAD_DIR/distill
DATA_DIR=$HEAD_DIR/data
LOGS_DIR=$HEAD_DIR/logs

export PYTHONPATH=$PYTHONPATH:$HEAD_DIR

python $CODE_DIR/algorithmic_trainer.py --model=transformer --task_name=identity --batch_size=128 &
python $CODE_DIR/algorithmic_trainer.py --model=transformer --task_name=addition --batch_size=128 &
python $CODE_DIR/algorithmic_trainer.py --model=transformer --task_name=multiplication --batch_size=128&
python $CODE_DIR/algorithmic_trainer.py --model=transformer --task_name=sort --batch_size=128 &
wait

