#!/bin/bash

#SBATCH --job-name=distill
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=5:00:00
#SBATCH --partition=gpu_shared
#SBATCH --gres=gpu:1

module load eb
module load Python/3.6.3-foss-2017b
module load CUDA/10.0.130
module load cuDNN/7.3.1-CUDA-10.0.130
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:/hpc/eb/Debian/cuDNN/7.3.1-CUDA-10.0.130/lib64:$LD_LIBRARY_PATH

cd /home/samigpu/Codes/SolutionDistillation

HEAD_DIR="/home/samigpu/Codes/SolutionDistillation"
CODE_DIR=$HEAD_DIR/distill
DATA_DIR=$HEAD_DIR/data
LOGS_DIR=$HEAD_DIR/logs

export PYTHONPATH=$PYTHONPATH:$HEAD_DIR

python $CODE_DIR/seq2seq_distiller.py \
 --batch_size=64 --teacher_hidden_dim=300 --student_hidden_dim=300 \
--teacher_model=bilstm --student_model=bilstm \
--teacher_train_embeddings=False --student_train_embeddings=False \
--student_decoder_depth=1 --student_encoder_depth=2 --teacher_decoder_depth=1 --teacher_encoder_depth=2 \
--student_input_dropout_keep_prob=0.75 --student_hidden_dropout_keep_prob=0.5 \
--teacher_input_dropout_keep_prob=0.75 --teacher_hidden_dropout_keep_prob=0.5 \
--student_learning_rate=0.001 \
--teacher_learning_rate=0.001 \
--decay_learning_rate=True --l2_rate=0.001 \
--student_encoder_attention_dir="top_down" \
--teacher_encoder_attention_dir="top_down" \
--train_student=True --train_teacher=True \
--distill_rep=False distill_logit=False \
--task_name=arithmatic --exp_name=_indp0_