#!/bin/bash

#SBATCH --job-name=distill_big_drop5
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=20:00:00
#SBATCH --partition=gpu_shared
#SBATCH --gres=gpu:1

module load surf-devel
module load 2019
module load Python/3.6.6-intel-2018b
module load CUDA/10.0.130
module load cuDNN/7.3.1-CUDA-10.0.130

#cd /home/samigpu/Codes/SolutionDistillation
source /home/samigpu/my_env/bin/activate

HEAD_DIR="/home/samigpu/Codes/SolutionDistillation"
CODE_DIR=$HEAD_DIR/distill
DATA_DIR=$HEAD_DIR/data
LOGS_DIR=$HEAD_DIR/logs

#mkdir "$TMPDIR"/samigpu

TMP_DATA_DIR=$DATA_DIR
#"$TMPDIR"/samigpu/data
TMP_LOGS_DIR=$LOGS_DIR
#"$TMPDIR"/samigpu/logs

#mkdir $TMP_DATA_DIR
#mkdir $TMP_LOGS_DIR

#Copy input file to scratch
#cp -r "$DATA_DIR"/* "$TMP_DATA_DIR"/
#cp -r "$LOGS_DIR"/* "$TMP_LOGS_DIR"/

echo "$TMP_LOGS_DIR"
export PYTHONPATH=$PYTHONPATH:$HEAD_DIR

CUDA_VISIBLE_DEVICES=0 python $CODE_DIR/seq2seq_distiller.py \
--log_dir="$TMP_LOGS_DIR" --data_dir="$TMP_DATA_DIR" \
--batch_size=128 --teacher_hidden_dim=512 --student_hidden_dim=64 \
--teacher_model=lstm --student_model=enc_utransformer \
--teacher_train_embeddings=True --student_train_embeddings=True \
--student_decoder_depth=1 --student_encoder_depth=4 --teacher_decoder_depth=1 --teacher_encoder_depth=2 \
--student_input_dropout_keep_prob=0.9 --student_hidden_dropout_keep_prob=1.0 \
--student_relu_dropout_keepprob=1.0 --student_postprocess_dropout_keepprob=0.9 \
--teacher_input_dropout_keep_prob=0.9 --teacher_hidden_dropout_keep_prob=0.5 \
--student_learning_rate=0.001 \
--teacher_learning_rate=0.001 \
--distill_learning_rate=0.001 \
--data_weight=0.0 \
--distill_logits_weight=1.0 \
--distill_rep_weight=0.0 \
--teacher_rep_distill_weight=0.0 \
--decay_learning_rate=True --l2_rate=0.0001 \
--student_encoder_attention_dir="top_down" \
--teacher_encoder_attention_dir="top_down" \
--train_student=True --train_teacher=True \
--distill_rep=False distill_logit=True \
--distill_temp=1.0 --teacher_temp=1.0 --student_temp=1.0 \
--task_name=arithmatic_simple_missinglength21_depth2_normal_biling --exp_name=_distill1-0_tdrop9-5_sdrop9-10-10-9_L20001_LR001_RUN4


#Copy input file to scratch
#cp -r  "$TMP_DATA_DIR"/* "$DATA_DIR"/
#cp -r  "$TMP_LOGS_DIR"/* "$LOGS_DIR"/

